services:
  - type: web
    name: food-delivery-api
    env: docker
    dockerContext: gs-serving-web-content-main/complete
    dockerfilePath: gs-serving-web-content-main/complete/Dockerfile
    plan: free
